<a href="https://colab.research.google.com/github/cpiedrahita142/MLCourse/blob/master/Lineal_Algebra_Practica_1_solucion_Carolina_piedrahita.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pregunta 1.

* Imprima la suma de las matrices A y B

$$ A =
\left(\begin{array}{cc} 
1 & 2\\
3 & 4\\
5 & 6
\end{array}\right) + B =
\left(\begin{array}{cc} 
6 & 5\\
4 & 3\\
2 & 1 
\end{array}\right)
$$ 

In [0]:
# Respuesta 1.
'su còdigo aqui'

import numpy as np

A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[6,5],[4,3],[2,1]])

C = A + B
print(C)

[[7 7]
 [7 7]
 [7 7]]


# Pregunta 2

* Imprima la suma de matriz + Escalar.

$$ M =
\left(\begin{array}{cc} 
6 & 3\\
9 & 5\\
4 & 8
\end{array}\right) + N =
\left(\begin{array}{cc} 
2.5 \\ 
\end{array}\right)
$$ 

In [0]:
M = np.array([[6,3],[9,5],[4,8]])
N = 2.5

k = M + N
print(k)

[[ 8.5  5.5]
 [11.5  7.5]
 [ 6.5 10.5]]


# Pregunta 3.

* Imprima la  transpuesta de la siguiente matriz  $J$  es decir $J^t$. 

$$ J =
\left(\begin{array}{cc} 
9 & 2 & 3\\
3 & 7 & 4 \\
5 & 6 & 9
\end{array}\right) 
$$ 

In [0]:
# Respuesta 2.
'su còdigo aqui'

J = np.array([[9,2,3],[3,7,4],[5,6,9]])
J_t = J.T
print(J_t)

[[9 3 5]
 [2 7 6]
 [3 4 9]]


# Pregunta 4.

* Para la matriz $J^t$, calcule su transpuesta para obtener la matriz original J.  

$$ J =
\left(\begin{array}{cc} 
9 & 2 & 3\\
3 & 7 & 4 \\
5 & 6 & 9
\end{array}\right) 
$$ 

In [0]:
# Respuesta 3.
'su còdigo aqui'
import numpy as np

J = np.array([[9,2,3],[3,7,4],[5,6,9]])
J_t = J.T
J_t_t = J_t.T
print(J_t_t)


[[9 2 3]
 [3 7 4]
 [5 6 9]]


# Pregunta 5.

* ¿ Cuales son los valores faltantes ? (en el orden en que aparecen las matrices) - MUltiplicación de matrices.

$$
\left(\begin{array}{cc} 
? & 2\\
0 & 2
\end{array}\right)
\left(\begin{array}{cc} 
1 & 0 \\ 
1 & ? 
\end{array}\right)
$$ 

 * para que la respuesta sea:
$
\left(
 \begin {array}{ll} 
1 & 0 \\
0   & 0
\end{array}
\right)
$

- [ A ] = 1 y 1
- [ B ] = 0 y 1
- [ C ] = 1 y 0
- [ D ] = 0 y 0

* Imprima el resultado y la respuesta.

In [0]:
# Respuesta 4.
'su còdigo aqui'

import numpy as np

# creacion de matrices 
A = np.array([[1,2],[0,2]])
B = np.array([[1,0],[0,0]])

# calculo de producto entre matrices
C = A * B

# imprimir la respuesta
print('la respuesta es:',"\n", C)

la respuesta es: 
 [[1 0]
 [0 0]]


# Pregunta 6.
* ¿ Cual es Producto Punto de las matrices $L$ y $K$ = : ?


$$ L =
\left(\begin{array}{cc} 
3 & 5 \\
7 & 1 \\
\end{array}\right) K =
\left(\begin{array}{cc} 
3 & 12  \\
6 & 4  \\
\end{array}\right)
$$ 

In [0]:
import numpy as np
L = np.array([[3,5],[7,1]])
K = np.array([[3,12],[6,4]])

LK_dot = L.dot(K)
print(LK_dot)


[[39 56]
 [27 88]]


**Calculo:** El producto punto entre ambas matrices será:

* primera fila de L x primera columna de K = 39
* primera fila de L x segunda columna de K = 56

$
\left(
 \begin {array}{ll} 
(3 * 3)  + (5 * 6) = 39 \\
(3 * 12) + (5 * 4) = 56 \\
(7 * 3)  + (1 * 6) = 27 \\
(3 * 12) + (5 * 4) = 56 \\
\end{array}
\right)
$

# Pregunta 7.

* ¿ Cual es el determinante de la siguiente matriz ? (imprima la respuesta)

$
\left(
\begin {array}{ll} 
1 & 2 & 0 \\
1 & 2 & 0 \\
0 & 1 & 1 \\
\end{array}
\right)
$

- [ A ] = 1 
- [ B ] = 0 
- [ C ] = 5
- [ D ] = -5



In [0]:
# Respuesta 3.
'su còdigo aqui'

import numpy as np
D = np.array([[1,2,0],[1,2,0], [0,1,1] ])
np.linalg.det(D)

0.0

# Pregunta 8.

* ¿ Cual es el determinante de la siguiente matriz ? (imprima la respuesta)

$
\left(
\begin {array}{ll} 
0 & 1 & 1 \\
1 & 0 & 0 \\
0 & 0 & 1 \\
\end{array}
\right)
$

- [ A ] = 0 
- [ B ] = -1 
- [ C ] = 3
- [ D ] = 1


In [0]:
import numpy as np
F = np.array([[0,1,1],[1,0,0], [0,0,1] ])

np.linalg.det(F)

-1.0

# Question 9

* ¿What is the missing value?
$$ 
\left(\begin{array}{cc} 
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{array}\right) 
\left(\begin{array}{cc} 
0 \\ 
? \\
0 \\
\end{array}\right) =
\left(\begin{array}{cc} 
4 \\ 
10 \\
16 \\
\end{array}\right)
$$ 

In [0]:

import numpy as np
X = np.array([[1,2,3],[4,5,6], [7,8,9] ])
Y = np.array([0, 2, 0])
prod = np.dot(X,Y)

print(prod)



[ 4 10 16]
